name: anchor
description: "Anchor app"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  iconly: ^1.0.1
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.1
  mask_text_input_formatter: ^2.8.0
  intl: ^0.19.0
  image_picker: ^1.0.7
  get_it: ^7.7.0
  auto_route: ^9.2.2
  flutter_bloc: ^8.1.6
  supabase_flutter: ^2.6.0
  smooth_corner: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  auto_route_generator: ^9.0.0

flutter_launcher_icons:
  android: "anchor_icon"
  ios: true
  image_path: "assets/images/anchor_logo.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/images/anchor_logo.png
    - assets/images/default_avatar.png
    - assets/images/welcome_illustration.svg

  fonts:
    - family: Onest
      fonts:
        - asset: fonts/Onest-Regular.ttf
        - asset: fonts/Onest-Black.ttf
        - asset: fonts/Onest-Bold.ttf
        - asset: fonts/Onest-ExtraBold.ttf
        - asset: fonts/Onest-ExtraLight.ttf
        - asset: fonts/Onest-Light.ttf
        - asset: fonts/Onest-Medium.ttf
        - asset: fonts/Onest-SemiBold.ttf
        - asset: fonts/Onest-Thin.ttf