// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChxawJ0Lfq8Xs0oKQk2LK7rSctIoayhJU',
    appId: '1:890195033510:web:adbfd5ef652d4e747f2367',
    messagingSenderId: '890195033510',
    projectId: 'anchor-f3a69',
    authDomain: 'anchor-f3a69.firebaseapp.com',
    storageBucket: 'anchor-f3a69.appspot.com',
    measurementId: 'G-5B4X495SDB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtjqRVePXgotY0xRoJ5PyO6AORwpe-vwU',
    appId: '1:890195033510:android:cf05cd00739dc0977f2367',
    messagingSenderId: '890195033510',
    projectId: 'anchor-f3a69',
    storageBucket: 'anchor-f3a69.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyASLr7j2qK8i3EFwwIGAAMWxkoZq4H_M',
    appId: '1:890195033510:ios:1a9de1350d2c35467f2367',
    messagingSenderId: '890195033510',
    projectId: 'anchor-f3a69',
    storageBucket: 'anchor-f3a69.appspot.com',
    iosBundleId: 'com.example.anchor',
  );
}
